import { Component, OnInit, Inject } from '@angular/core';
import { ActivatedRoute,Router} from "@angular/router";
import { FormArray, FormBuilder, FormControl, Validators } from '@angular/forms';
import { MatDialogRef, MatDialog, MAT_DIALOG_DATA } from '@angular/material/dialog';

import { SuppliersService } from '../suppliers.service';
 import { ISuppliers
 } from '../isuppliers';
import { BaseNewComponent, FieldType, PickerDialogService } from 'src/app/common/shared';
import { ErrorService } from 'src/app/core/services/error.service';


@Component({
  selector: 'app-suppliers-new',
  templateUrl: './suppliers-new.component.html',
  styleUrls: ['./suppliers-new.component.scss']
})
export class SuppliersNewComponent extends BaseNewComponent<ISuppliers> implements OnInit {
  
    title:string = "New Suppliers";
	constructor(
		public formBuilder: FormBuilder,
		public router: Router,
		public route: ActivatedRoute,
		public dialog: MatDialog,
		public dialogRef: MatDialogRef<SuppliersNewComponent>,
		@Inject(MAT_DIALOG_DATA) public data: any,
		public pickerDialogService: PickerDialogService,
		public suppliersService: SuppliersService,
		public errorService: ErrorService,
	) {
		super(formBuilder, router, route, dialog, dialogRef, data, pickerDialogService, suppliersService, errorService);
	}
 
		ngOnInit() {
		this.entityName = 'Suppliers';
		this.setAssociations();
		super.ngOnInit();
    	this.setForm();
		this.checkPassedData();
        }


	setForm(){
 		this.itemForm = this.formBuilder.group({
      contactEmail: [''],
      name: ['', Validators.required],
    });
    
    this.fields = [
              {
      		  name: 'contactEmail',
      		  label: 'contact Email',
      		  isRequired: false,
      		  isAutoGenerated: false,
      	      type: FieldType.String,
      	    },
              {
      		  name: 'name',
      		  label: 'name',
      		  isRequired: true,
      		  isAutoGenerated: false,
      	      type: FieldType.String,
      	    },
              {
      		  name: 'supplierId',
      		  label: 'supplier Id',
      		  isRequired: true,
      		  isAutoGenerated: true,
      	      type: FieldType.Number,
      	    },
		];
	}
	 
	setAssociations(){
  	
		this.associations = [
		];
		this.parentAssociations = this.associations.filter(association => {
			return (!association.isParent);
		});

	}
	
	onSubmit() {
		let suppliers = this.itemForm.getRawValue();



        super.onSubmit(suppliers);

	}
    
}
