import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from "@angular/router";
import { FormArray, FormBuilder, FormControl, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material/dialog';

import { SuppliersService } from '../suppliers.service';
import { ISuppliers
 } from '../isuppliers';
import { BaseDetailsComponent, FieldType, PickerDialogService } from 'src/app/common/shared';
import { ErrorService } from 'src/app/core/services/error.service';


@Component({
  selector: 'app-suppliers-details',
  templateUrl: './suppliers-details.component.html',
  styleUrls: ['./suppliers-details.component.scss']
})
export class SuppliersDetailsComponent extends BaseDetailsComponent<ISuppliers> implements OnInit {
	title = 'Suppliers';
	parentUrl = 'suppliers';
	constructor(
		public formBuilder: FormBuilder,
		public router: Router,
		public route: ActivatedRoute,
		public dialog: MatDialog,
		public suppliersService: SuppliersService,
		public pickerDialogService: PickerDialogService,
		public errorService: ErrorService,
	) {
		super(formBuilder, router, route, dialog, pickerDialogService, suppliersService, errorService);
  }

	ngOnInit() {
		this.entityName = 'Suppliers';
		this.setAssociations();
		super.ngOnInit();
		this.setForm();
    	this.getItem();
	}
  
  setForm(){
    this.itemForm = this.formBuilder.group({
      contactEmail: [''],
      name: ['', Validators.required],
      supplierId: [{value: '', disabled: true}, Validators.required],
      
    });
    
    this.fields = [
        {
		  name: 'contactEmail',
		  label: 'contact Email',
		  isRequired: false,
		  isAutoGenerated: false,
	      type: FieldType.String,
	    },
        {
		  name: 'name',
		  label: 'name',
		  isRequired: true,
		  isAutoGenerated: false,
	      type: FieldType.String,
	    },
        {
		  name: 'supplierId',
		  label: 'supplier Id',
		  isRequired: true,
		  isAutoGenerated: true,
	      type: FieldType.Number,
	    },
      ];
      
  }
  
  onItemFetched(item: ISuppliers) {
    this.item = item;
     this.itemForm.patchValue(item);

  }
  
  setAssociations(){
    this.associations = [
      {
        column: [
	        {
	          key: 'supplierId',
	          value: undefined,
	          referencedkey: 'supplierId'
			},
		],
		isParent: true,
		table: 'productsuppliers',
		type: 'OneToMany',
		label: 'productsuppliers',
		},
		];
		
		this.childAssociations = this.associations.filter(association => {
			return (association.isParent);
		});

		this.parentAssociations = this.associations.filter(association => {
			return (!association.isParent);
		});
	}
	
	onSubmit() {
		let suppliers = this.itemForm.getRawValue();



        super.onSubmit(suppliers);
	}
}
