import { Component, OnInit, Inject } from '@angular/core';
import { ActivatedRoute,Router} from "@angular/router";
import { FormArray, FormBuilder, FormControl, Validators } from '@angular/forms';
import { MatDialogRef, MatDialog, MAT_DIALOG_DATA } from '@angular/material/dialog';

import { OrderitemsService } from '../orderitems.service';
 import { IOrderitems
 } from '../iorderitems';
import { BaseNewComponent, FieldType, PickerDialogService } from 'src/app/common/shared';
import { ErrorService } from 'src/app/core/services/error.service';

import { OrdersService } from 'src/app/entities/orders/orders.service';
import { ProductsService } from 'src/app/entities/products/products.service';

@Component({
  selector: 'app-orderitems-new',
  templateUrl: './orderitems-new.component.html',
  styleUrls: ['./orderitems-new.component.scss']
})
export class OrderitemsNewComponent extends BaseNewComponent<IOrderitems> implements OnInit {
  
    title:string = "New Orderitems";
	constructor(
		public formBuilder: FormBuilder,
		public router: Router,
		public route: ActivatedRoute,
		public dialog: MatDialog,
		public dialogRef: MatDialogRef<OrderitemsNewComponent>,
		@Inject(MAT_DIALOG_DATA) public data: any,
		public pickerDialogService: PickerDialogService,
		public orderitemsService: OrderitemsService,
		public errorService: ErrorService,
		public ordersService: OrdersService,
		public productsService: ProductsService,
	) {
		super(formBuilder, router, route, dialog, dialogRef, data, pickerDialogService, orderitemsService, errorService);
	}
 
		ngOnInit() {
		this.entityName = 'Orderitems';
		this.setAssociations();
		super.ngOnInit();
    	this.setForm();
		this.checkPassedData();
        }


	setForm(){
 		this.itemForm = this.formBuilder.group({
      priceAtOrderTime: ['', Validators.required],
      quantity: ['', Validators.required],
      orderId: [''],
      ordersDescriptiveField: [''],
      productId: [''],
      productsDescriptiveField: [''],
    });
    
    this.fields = [
              {
      		  name: 'orderItemId',
      		  label: 'order Item Id',
      		  isRequired: true,
      		  isAutoGenerated: true,
      	      type: FieldType.Number,
      	    },
              {
      		  name: 'priceAtOrderTime',
      		  label: 'price At Order Time',
      		  isRequired: true,
      		  isAutoGenerated: false,
      	      type: FieldType.Number,
      	    },
              {
      		  name: 'quantity',
      		  label: 'quantity',
      		  isRequired: true,
      		  isAutoGenerated: false,
      	      type: FieldType.Number,
      	    },
		];
	}
	 
	setAssociations(){
  	
		this.associations = [
			{
				column: [
					{
						key: 'orderId',
						value: undefined,
						referencedkey: 'orderId'
					},
					  
				],
				isParent: false,
				table: 'orders',
				type: 'ManyToOne',
				service: this.ordersService,
				label: 'orders',
				descriptiveField: 'ordersDescriptiveField',
				referencedDescriptiveField: 'orderId',
		    
			},
			{
				column: [
					{
						key: 'productId',
						value: undefined,
						referencedkey: 'productId'
					},
					  
				],
				isParent: false,
				table: 'products',
				type: 'ManyToOne',
				service: this.productsService,
				label: 'products',
				descriptiveField: 'productsDescriptiveField',
				referencedDescriptiveField: 'productId',
		    
			},
		];
		this.parentAssociations = this.associations.filter(association => {
			return (!association.isParent);
		});

	}
	
	onSubmit() {
		let orderitems = this.itemForm.getRawValue();



        super.onSubmit(orderitems);

	}
    
}
