import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from "@angular/router";
import { FormArray, FormBuilder, FormControl, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material/dialog';

import { CustomersService } from '../customers.service';
import { ICustomers
 } from '../icustomers';
import { BaseDetailsComponent, FieldType, PickerDialogService } from 'src/app/common/shared';
import { ErrorService } from 'src/app/core/services/error.service';


@Component({
  selector: 'app-customers-details',
  templateUrl: './customers-details.component.html',
  styleUrls: ['./customers-details.component.scss']
})
export class CustomersDetailsComponent extends BaseDetailsComponent<ICustomers> implements OnInit {
	title = 'Customers';
	parentUrl = 'customers';
	constructor(
		public formBuilder: FormBuilder,
		public router: Router,
		public route: ActivatedRoute,
		public dialog: MatDialog,
		public customersService: CustomersService,
		public pickerDialogService: PickerDialogService,
		public errorService: ErrorService,
	) {
		super(formBuilder, router, route, dialog, pickerDialogService, customersService, errorService);
  }

	ngOnInit() {
		this.entityName = 'Customers';
		this.setAssociations();
		super.ngOnInit();
		this.setForm();
    	this.getItem();
	}
  
  setForm(){
    this.itemForm = this.formBuilder.group({
      createdAt: [''],
	  createdAtTime: [''],
      customerId: [{value: '', disabled: true}, Validators.required],
      email: ['', Validators.required],
      name: ['', Validators.required],
      
    });
    
    this.fields = [
        {
		  name: 'createdAt',
		  label: 'created At',
		  isRequired: false,
		  isAutoGenerated: false,
		  type: FieldType.Date,
		},
		{
		  name: 'createdAtTime',
		  label: 'created At Time',
		  isRequired: false,
		  isAutoGenerated: false,
		  type: FieldType.Time
	    },
        {
		  name: 'customerId',
		  label: 'customer Id',
		  isRequired: true,
		  isAutoGenerated: true,
	      type: FieldType.Number,
	    },
        {
		  name: 'email',
		  label: 'email',
		  isRequired: true,
		  isAutoGenerated: false,
	      type: FieldType.String,
	    },
        {
		  name: 'name',
		  label: 'name',
		  isRequired: true,
		  isAutoGenerated: false,
	      type: FieldType.String,
	    },
      ];
      
  }
  
  onItemFetched(item: ICustomers) {
    this.item = item;
    this.itemForm.get('createdAt')?.setValue(item.createdAt? new Date(item.createdAt): null);
    this.itemForm.get('createdAtTime')?.setValue(this.customersService.formatDateStringToAMPM(item.createdAt));
     this.itemForm.patchValue(item);

  }
  
  setAssociations(){
    this.associations = [
      {
        column: [
	        {
	          key: 'customerId',
	          value: undefined,
	          referencedkey: 'customerId'
			},
		],
		isParent: true,
		table: 'orders',
		type: 'OneToMany',
		label: 'orders',
		},
		];
		
		this.childAssociations = this.associations.filter(association => {
			return (association.isParent);
		});

		this.parentAssociations = this.associations.filter(association => {
			return (!association.isParent);
		});
	}
	
	onSubmit() {
		let customers = this.itemForm.getRawValue();


	    customers.createdAt = this.dataService.combineDateAndTime(customers.createdAt, customers.createdAtTime);
	    delete customers.createdAtTime;

        super.onSubmit(customers);
	}
}
